
# Stages der pipeline (Build zum bauen der Anwendung)
stages:
  - build
# - test
# - deploy

variables:
  DOCKER_IMAGE_1: "protogen_backend_node"
  DOCKER_IMAGE_2: "protogen_backend_db"
  DOCKER_IMAGE_3: "protogen_frontend_nextjs"

build_images:
  stage: build
  tags:
    - protogen-runner-v2
  image: docker:stable
  variables:
    IMAGE_TAG_BACKEND_NODE: $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_1:$CI_COMMIT_REF_SLUG
    IMAGE_TAG_BACKEND_DB: $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_2:$CI_COMMIT_REF_SLUG
    IMAGE_TAG_FRONTEND_NEXTJS: $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_3:$CI_COMMIT_REF_SLUG
  script:
    # bauen der Docker images
    - docker build -t $IMAGE_TAG_BACKEND_NODE -f backend/Dockerfile .
    - docker build -t $IMAGE_TAG_BACKEND_DB ./database
    - docker build -t $IMAGE_TAG_FRONTEND_NEXTJS -f Dockerfile .
  after_script:
    # löschen der images und anschließendes säubern von <none>-tags die beim Untag&Delete(muss noch überarbeitet werden) entstehen
    # - docker rmi $IMAGE_TAG_BACKEND_NODE $IMAGE_TAG_BACKEND_DB $IMAGE_TAG_FRONTEND_NEXTJS
    #- docker rmi $(docker image -f "dangling=true" -q)
  only:
    - dev


#test_node_backend:
#  stage: test
#  tags:
#    - npm
#  script:
#    - npm install backend/package.json 
#    - npm test
#  only:
#    - feature/CI


# build_backend_node:
#  stage: build
#  tags:
#    - protogen-runner
#  services:
#    - name: docker:dind
#      entrypoint: ["env", "-u", "DOCKER_HOST"]
#      command: ["dockerd-entrypoint.sh"] 
#  variables:
#    IMAGE_TAG: $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_1:$CI_COMMIT_REF_SLUG
#  script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - docker build -t $IMAGE_TAG -f backend/Dockerfile .
#    - docker push $IMAGE_TAG
#  only:
#    - feature/CI 

#build_backend_db:
#  stage: build
#  tags:
#    - protogen-runner
#  services:
#    - name: docker:dind
#      entrypoint: ["env", "-u", "DOCKER_HOST"]
#      command: ["dockerd-entrypoint.sh"] 
#  variables:
#    IMAGE_TAG: $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_2:$CI_COMMIT_REF_SLUG
#  script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - docker build -t $IMAGE_TAG ./database
#     - docker push $IMAGE_TAG
#  only:
#    - feature/CI 

#build_frontend_nextjs:
#  stage: build
#  tags:
#    - protogen-runner
#  services:
#    - name: docker:dind
#      entrypoint: ["env", "-u", "DOCKER_HOST"]
#      command: ["dockerd-entrypoint.sh"] 
#  variables:
#    IMAGE_TAG: $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_3:$CI_COMMIT_REF_SLUG
#  script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - docker build -t $IMAGE_TAG -f Dockerfile .
#    - docker push $IMAGE_TAG
#  only:
#    - feature/CI 
