## Stages / In Welher Reihenfolge welche Jobs abgearbeitet werden sollen

stages:
  - build
# - test
# - deploy

build_backend:
  stage: build
  #tags:
  #  - alpine
  image: docker:latest
  script:
    #- apk add --update docker openrc
    #- mkdir -p /run/openrc 
    #- touch /run/openrc/softlevel
    - service docker status
    - echo `docker --version`
  only:
    - feature/CI
