## Stages / In Welher Reihenfolge welche Jobs abgearbeitet werden sollen


  
stages:
  - build
# - test
# - deploy

build_backend:
  stage: build
  tags:
    - protogen-runner
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"] 
  variables:
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "$GITLAB_USER_LOGIN - Build"
    - docker build -t protogen_backend:latest -f backend/Dockerfile .
  only:
    - feature/CI
