## Stages / In Welher Reihenfolge welche Jobs abgearbeitet werden sollen

stages:
  - build
# - test
# - deploy

build_backend:
  stage: build
  tags:
    - alpine
  script:
    - apk add --update docker openrc
    - mkdir -p /run/openrc 
    - touch /run/openrc/softlevel
    - while [ ! -S /var/run/docker.sock ]; do echo 'Waiting for Docker to start'; sleep 1; done
    - docker info
  only:
    - feature/CI
