## Stages / In Welher Reihenfolge welche Jobs abgearbeitet werden sollen

stages:
  - build
# - test
# - deploy

build_frontend:
  stage: build
  tags:
    - alpine
  script:
    - echo "$GITLAB_USER_LOGIN - Test"
    - docker build -t protogen_backend:latest -f backend/Dockerfile .
  only:
    - feature/CI
