## Stages / In Welher Reihenfolge welche Jobs abgearbeitet werden sollen

stages:
  - build
# - test
# - deploy

build_backend:
  stage: build
  image: docker:latest
  script:
    - echo "done"
  only:
    - feature/CI
