## Stages / In Welher Reihenfolge welche Jobs abgearbeitet werden sollen

stages:
  - build
# - test
# - deploy

build_backend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  tags:
    - kaniko
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
    - echo "Done"
  only:
    - feature/CI
