## Stages / In Welher Reihenfolge welche Jobs abgearbeitet werden sollen

stages:
  - build
# - test
# - deploy

build_backend:
  stage: build
  tags:
    - alpine
  script:
# installiere in einerm docker alpine docker :D
    - apk add --update docker openrc
# Warte bis docker läuft
    - while [ ! -S /var/run/docker.sock ]; do echo 'Waiting for Docker to start'; sleep 1; done
    - echo "$GITLAB_USER_LOGIN - Test"
    - docker build -t protogen_backend:latest -f backend/Dockerfile .
  only:
    - feature/CI
