## Stages / In Welher Reihenfolge welche Jobs abgearbeitet werden sollen

stages:
  - build
# - test
# - deploy

build_backend:
  stage: build
  services:
    - docker:dind
  tags:
    - protogen-runner
  script:
    #- apk add --update docker openrc
    #- mkdir -p /run/openrc 
    #- touch /run/openrc/softlevel
    - echo "$GITLAB_USER_LOGIN - Build"
    - docker --version
    - echo `service docker status`
    #- docker build -t protogen_backend:latest -f backend/Dockerfile .
    #- echo `docker --version` 
  only:
    - feature/CI
