## Stages / In Welher Reihenfolge welche Jobs abgearbeitet werden sollen

stages:
  - build
# - test
# - deploy

build_backend:
  stage: build
  tags:
    - protogen-runner
  script:
    #- apk add --update docker openrc
    #- mkdir -p /run/openrc 
    #- touch /run/openrc/softlevel
    - docker --version
    #- echo `docker --version`
  only:
    - feature/CI
