## Stages / In Welher Reihenfolge welche Jobs abgearbeitet werden sollen

stages:
  - build
# - test
# - deploy

build_backend:
  stage: build
  tags:
    - alpine
  script:
# installiere in einerm docker alpine docker :D
    - apk add --update docker openrc
    - touch /run/openrc/softlevel
    - service docker status
# Warte bis docker läuft
    - echo "$GITLAB_USER_LOGIN - Test"
    - docker build -t protogen_backend:latest -f backend/Dockerfile .
  only:
    - feature/CI
