version: "3"
services:
  node-app: 
    build: 
      context: ./backend
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm run start
    env_file:
      - ./backend/.env