version: "3"
services:
  frontend:
    container_name: protogen_frontend
    build: 
      context: ./frontend
      args: 
        NODE_ENV: development
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    command: npm run start
    env_file:
      - ./.env

  backend:
    container_name: protogen_backend
    build: 
      context: ./backend
      args: 
        NODE_ENV: production
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=8080
      - NODE_ENV=production
    command: npm run start
    depends_on:
      - postgres
    env_file:
      - ./.env

  postgres:
    container_name: protogen_postgres
    build: ./database
    env_file: ./.env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes: 
      - protogen-postgres:/var/lib/postgresql/data

volumes:
  protogen-postgres: